# Generated by Django 3.2.6 on 2021-08-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel_name', models.CharField(max_length=100)),
                ('Channel_image', models.ImageField(upload_to='')),
                ('Category', models.ManyToManyField(to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_name', models.CharField(max_length=200)),
                ('Program_time', models.DateTimeField()),
                ('Channel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.channel')),
            ],
        ),
    ]
