# Generated by Django 3.2.6 on 2021-08-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_channel_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
