# Generated by Django 3.2.6 on 2021-08-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210817_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_ru',
            new_name='category_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_uz',
            new_name='category_uz',
        ),
    ]
